export interface AfricanCountry {
  iso2: string;
  name: string;
  logisticsZone: string;
}

export const africanCountries: AfricanCountry[] = [
  { iso2: 'DZ', name: 'Algeria', logisticsZone: 'AFRICA_NORTH' },
  { iso2: 'AO', name: 'Angola', logisticsZone: 'AFRICA_CENTRAL' },
  { iso2: 'BJ', name: 'Benin', logisticsZone: 'AFRICA_WEST' },
  { iso2: 'BW', name: 'Botswana', logisticsZone: 'AFRICA_SOUTHERN' },
  { iso2: 'BF', name: 'Burkina Faso', logisticsZone: 'AFRICA_WEST' },
  { iso2: 'BI', name: 'Burundi', logisticsZone: 'AFRICA_EAST' },
  { iso2: 'CV', name: 'Cabo Verde', logisticsZone: 'AFRICA_ISLANDS' },
  { iso2: 'CM', name: 'Cameroon', logisticsZone: 'AFRICA_CENTRAL' },
  { iso2: 'CF', name: 'Central African Republic', logisticsZone: 'AFRICA_CENTRAL' },
  { iso2: 'TD', name: 'Chad', logisticsZone: 'AFRICA_CENTRAL' },
  { iso2: 'KM', name: 'Comoros', logisticsZone: 'AFRICA_ISLANDS' },
  { iso2: 'CG', name: 'Congo', logisticsZone: 'AFRICA_CENTRAL' },
  { iso2: 'CD', name: 'Congo, Democratic Republic of the', logisticsZone: 'AFRICA_CENTRAL' },
  { iso2: 'CI', name: "Cote d'Ivoire", logisticsZone: 'AFRICA_WEST' },
  { iso2: 'DJ', name: 'Djibouti', logisticsZone: 'AFRICA_EAST' },
  { iso2: 'EG', name: 'Egypt', logisticsZone: 'AFRICA_NORTH' },
  { iso2: 'GQ', name: 'Equatorial Guinea', logisticsZone: 'AFRICA_CENTRAL' },
  { iso2: 'ER', name: 'Eritrea', logisticsZone: 'AFRICA_EAST' },
  { iso2: 'SZ', name: 'Eswatini', logisticsZone: 'AFRICA_SOUTHERN' },
  { iso2: 'ET', name: 'Ethiopia', logisticsZone: 'AFRICA_EAST' },
  { iso2: 'GA', name: 'Gabon', logisticsZone: 'AFRICA_CENTRAL' },
  { iso2: 'GM', name: 'Gambia', logisticsZone: 'AFRICA_WEST' },
  { iso2: 'GH', name: 'Ghana', logisticsZone: 'AFRICA_WEST' },
  { iso2: 'GN', name: 'Guinea', logisticsZone: 'AFRICA_WEST' },
  { iso2: 'GW', name: 'Guinea-Bissau', logisticsZone: 'AFRICA_WEST' },
  { iso2: 'KE', name: 'Kenya', logisticsZone: 'AFRICA_EAST' },
  { iso2: 'LS', name: 'Lesotho', logisticsZone: 'AFRICA_SOUTHERN' },
  { iso2: 'LR', name: 'Liberia', logisticsZone: 'AFRICA_WEST' },
  { iso2: 'LY', name: 'Libya', logisticsZone: 'AFRICA_NORTH' },
  { iso2: 'MG', name: 'Madagascar', logisticsZone: 'AFRICA_ISLANDS' },
  { iso2: 'MW', name: 'Malawi', logisticsZone: 'AFRICA_EAST' },
  { iso2: 'ML', name: 'Mali', logisticsZone: 'AFRICA_WEST' },
  { iso2: 'MR', name: 'Mauritania', logisticsZone: 'AFRICA_WEST' },
  { iso2: 'MU', name: 'Mauritius', logisticsZone: 'AFRICA_ISLANDS' },
  { iso2: 'MA', name: 'Morocco', logisticsZone: 'AFRICA_NORTH' },
  { iso2: 'MZ', name: 'Mozambique', logisticsZone: 'AFRICA_EAST' },
  { iso2: 'NA', name: 'Namibia', logisticsZone: 'AFRICA_SOUTHERN' },
  { iso2: 'NE', name: 'Niger', logisticsZone: 'AFRICA_WEST' },
  { iso2: 'NG', name: 'Nigeria', logisticsZone: 'AFRICA_WEST' },
  { iso2: 'RW', name: 'Rwanda', logisticsZone: 'AFRICA_EAST' },
  { iso2: 'ST', name: 'Sao Tome and Principe', logisticsZone: 'AFRICA_ISLANDS' },
  { iso2: 'SN', name: 'Senegal', logisticsZone: 'AFRICA_WEST' },
  { iso2: 'SC', name: 'Seychelles', logisticsZone: 'AFRICA_ISLANDS' },
  { iso2: 'SL', name: 'Sierra Leone', logisticsZone: 'AFRICA_WEST' },
  { iso2: 'SO', name: 'Somalia', logisticsZone: 'AFRICA_EAST' },
  { iso2: 'ZA', name: 'South Africa', logisticsZone: 'AFRICA_SOUTHERN' },
  { iso2: 'SS', name: 'South Sudan', logisticsZone: 'AFRICA_EAST' },
  { iso2: 'SD', name: 'Sudan', logisticsZone: 'AFRICA_NORTH' },
  { iso2: 'TZ', name: 'Tanzania', logisticsZone: 'AFRICA_EAST' },
  { iso2: 'TG', name: 'Togo', logisticsZone: 'AFRICA_WEST' },
  { iso2: 'TN', name: 'Tunisia', logisticsZone: 'AFRICA_NORTH' },
  { iso2: 'UG', name: 'Uganda', logisticsZone: 'AFRICA_EAST' },
  { iso2: 'EH', name: 'Western Sahara', logisticsZone: 'AFRICA_NORTH' },
  { iso2: 'ZM', name: 'Zambia', logisticsZone: 'AFRICA_EAST' },
  { iso2: 'ZW', name: 'Zimbabwe', logisticsZone: 'AFRICA_EAST' },
];
