export interface QuoteConfig {
  gerberFileName?: string;
  productType: 'standard_pcb' | 'advanced_pcb' | 'fpc_rigid_flex' | 'pcb_assembly' | 'smt_stencil' | 'cnc_3d';
  baseMaterial: 'FR4' | 'Flex' | 'Aluminum' | 'Aluminium' | 'Copper Core' | 'Rogers' | 'PTFE Teflon';
  layers: number;
  length: number;
  width: number;
  unit: 'mm' | 'inch';
  quantity: number;
  differentDesigns: number;
  usageType: 'consumer_industrial' | 'aerospace' | 'medical';
  deliveryFormat: 'single_pcb' | 'customer_panel' | 'panel_by_partner';
  thickness: string;
  solderMaskColor: string;
  silkscreenColor: string;
  surfaceFinish: string;
  viaCovering: string;
  productionSpeed: 'standard' | 'express_24h' | 'pcba_24h';
  outerCopperWeight: string;
  innerCopperWeight: string;
  impedanceControl: boolean;
  minimumViaHole: string;
  viaDiameter: string;
  goldFingers: boolean;
  castellatedHoles: boolean;
  edgePlating: boolean;
  blindBuriedVias: boolean;
  viaInPad: boolean;
  peelableMask: boolean;
  carbonInk: boolean;
  countersink: boolean;
  pressFitHoles: boolean;
  coverlayThickness: string;
  stiffenerType: string;
  stiffenerThickness: string;
  emiShieldingFilm: boolean;
  cuttingMethod: string;
  adhesiveType: string;
  orderNumberMarking: boolean;
  markingLocationSpecified: boolean;
  removeMarking: boolean;
  twoDBarcode: boolean;
  serialNumber: boolean;
  flyingProbe: boolean;
  fullElectricalTest: boolean;
  randomElectricalTest: boolean;
  fourWireKelvinTest: boolean;
  aoi: boolean;
  assemblyRequired: boolean;
  assemblySide: string;
  bomFileName?: string;
  cplFileName?: string;
  componentSourcing: string;
  confirmPartsPlacement: boolean;
  stencilRequired: boolean;
  stencilType: string;
  stencilSize: string;
  stencilThickness: string;
  stencilFrame: boolean;
  electroPolishing: boolean;
  engraving: boolean;
  destinationCountry: string;
  shippingMode: 'economy' | 'standard' | 'express';
  liveShippingRateId?: string;
  liveShippingCarrier?: string;
  liveShippingService?: string;
  liveShippingAmount?: number;
  liveShippingCurrency?: string;
  liveShippingTransitTime?: string;
  insuranceRequired: boolean;
  parserConfidence?: number;
  gerberComplexity?: 'low' | 'medium' | 'high' | 'unknown';
  holesCount?: number;
  hasSlots?: boolean;
  detectedLayers?: number;
  detectedWidthMm?: number;
  detectedHeightMm?: number;
  boardAreaCm2?: number;
}

export interface PricingBreakdown {
  partnerManufacturingCost: number;
  partnerHandlingCost: number;
  chinaToFranceLogistics: number;
  franceProcessingFee: number;
  franceToAfricaDelivery: number;
  paymentProcessingFee: number;
  kendronicsServiceFee: number;
  supplierEstimatedPrice?: number;
  pcbClientPrice?: number;
  smartBufferMultiplier?: number;
  smartBufferRiskScore?: number;
  smartBufferConfidence?: 'low' | 'medium' | 'high';
  smartBufferBucketKey?: string;
  viaCoveringFee: number;
  surfaceFinishFee: number;
  productionSpeedFee: number;
  finalTotal: number;
  displayTotalBeforeAdjustment: number;
  deliveryWeightKg: number;
  shippingCarrier: string;
  estimatedShippingTime: string;
  estimatedLeadTime: string;
  pricingSource: 'local_calibrated' | 'supplier_api';
  transparencyNote: string;
}
